In [1]:
import numpy as np

arr=np.array([1,2,3,4,5])
print(arr*2)

[ 2  4  6  8 10]


In [3]:
list1=[1,2,3,4,5]
b=[i*2 for i in list1]
print(b)

[2, 4, 6, 8, 10]


In [4]:
print(type(arr))

<class 'numpy.ndarray'>


In [5]:
arr=np.array([1,2,3,4,5,"str"])
print(arr)


['1' '2' '3' '4' '5' 'str']


In [6]:
arr=np.array([1,2,3,4,5,"str",8.8])
print(arr)

['1' '2' '3' '4' '5' 'str' '8.8']


In [7]:
arr=np.array([1,2,3,4,5,8.8,True])
print(arr)

[1.  2.  3.  4.  5.  8.8 1. ]


In [8]:
arr=np.array([1,2,3,4,5,True])
print(arr)

[1 2 3 4 5 1]


In [9]:
arr=np.array([1,2,3,4,5,"str",8.8,True])
print(arr)

['1' '2' '3' '4' '5' 'str' '8.8' 'True']


In [2]:
# making matrix in array
arr=np.array([[1,2,3],[10,4,29],[2,3,4]])
print(arr)

[[ 1  2  3]
 [10  4 29]
 [ 2  3  4]]


In [3]:
#slicing in array:-
print(arr[0][2])
print(arr[1][2])

3
29


In [4]:
print(arr.ndim)

2


In [13]:
print(arr.dtype)
print(arr.shape)
print(arr.reshape(3,3))

int32
(3, 3)
[[ 1  2  3]
 [10  4 29]
 [ 2  3  4]]


In [19]:
print(arr.reshape(3,2))

[[ 1  2]
 [ 3 10]
 [ 4 29]]


In [2]:
my = {
    "car" : ["ford","kia","audi","benz","bmw"],
    "no" : [1,2,3,4,5],
    "orgin" : [1999,1998,1997,1996,1995]
}

import pandas as pd
df1=pd.DataFrame(my)
print(df1)

    car  no  orgin
0  ford   1   1999
1   kia   2   1998
2  audi   3   1997
3  benz   4   1996
4   bmw   5   1995


In [4]:
# slicing:-
print(df1[0:4])

    car  no  orgin
0  ford   1   1999
1   kia   2   1998
2  audi   3   1997
3  benz   4   1996


In [3]:
print(df1.loc[4])

car       bmw
no          5
orgin    1995
Name: 4, dtype: object


In [33]:
my = {
    "car" : ["ford","kia","audi","benz","bmw"],
    "no" : [1,2,3,4,5],
    "orgin" : [1999,1998,1997,1996,1995]
}

import pandas as pd
df2=pd.DataFrame(my,index=["car1","car2","car3","car4","car5"])
print(df2)


       car  no  orgin
car1  ford   1   1999
car2   kia   2   1998
car3  audi   3   1997
car4  benz   4   1996
car5   bmw   5   1995


In [34]:
print(df2.loc["car1":"car4"])

print(df2.loc["car1"])


       car  no  orgin
car1  ford   1   1999
car2   kia   2   1998
car3  audi   3   1997
car4  benz   4   1996
car      ford
no          1
orgin    1999
Name: car1, dtype: object


In [40]:
# slicing:-
print(df2[0:4])

       car  no  orgin
car1  ford   1   1999
car2   kia   2   1998
car3  audi   3   1997
car4  benz   4   1996


In [37]:
# slicing:-
print(df2[2:4])

       car  no  orgin
car3  audi   3   1997
car4  benz   4   1996


# 

In [3]:
import pandas as pd
df = pd.read_csv('python/pandas/data.csv.txt')
print(df)

FileNotFoundError: [Errno 2] No such file or directory: 'python/pandas/data.csv.txt'